name: Auto-generate Jio Files

on:
  schedule:
    - cron: "*/30 * * * *"   # প্রতি 30 মিনিটে রান হবে
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyzipper==0.3.6

      # 4️⃣ Extract protected app.zip
      - name: Extract protected app.zip
        env:
          ZIP_PWD: ${{ secrets.ZIP_PWD }}
        run: |
          python run.py

      # 5️⃣ Run app.py to generate files
      - name: Run app.py
        run: |
          python app.py

      # 6️⃣ Commit and push generated files
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Auto api updated made by cooder boy $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
